
name: Antonio Maradiaga

#SEO
description: Collection of things I'm interested in / working on
url: http://www.ajmaradiaga.com
twitter:
  username: ajmrdg

# Includes an icon in the footer for each username you enter
footer-links:
  email: me@ajmaradiaga.com
  github: ajmaradiaga
  linkedin: ajmaradiaga
  twitter: ajmrdg

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  
whitelist:
  - jekyll-redirect-from
  
theme: jekyll-theme-tactile

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
